version: '3.3'
services: 
  ui-e2e-dev:
    image: madie
    tty: true
    build: .
    container_name: cydev
    environment:
      - CYPRESS_DEV_USERNAME=${CYPRESS_DEV_USERNAME}
      - CYPRESS_DEV_PASSWORD=${CYPRESS_DEV_PASSWORD}
      - CYPRESS_TEST_USERNAME=${CYPRESS_TEST_USERNAME}
      - CYPRESS_TEST_PASSWORD=${CYPRESS_TEST_PASSWORD}
      - CYPRESS_VSAC_API_KEY=${CYPRESS_VSAC_API_KEY}
    volumes:
      - ./mochawesome-report:/app/mochawesome-report
